name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://124-238-119-12.pd1.cjjd19.com:30443/download-cdn.cjjd19.com/123-749/14fbd223/1821234343-0/14fbd2235a0c7f28f88007a4b159c2ed/c-m6?v=5&t=1734256329&s=17342563298f6c2a3e2b83a70118d1aa1b8f15e38c&r=6VRGKE&bzc=2&bzs=313832313233343334333a37373733393031383a323535373332343630303a31383231323334333433&filename=Z6Lite_ZUI12_Beta1_ByLZY.zip&x-mf-biz-cid=180ee1d8-04c4-43e1-8ef0-58d30713b544-6eaa77&cache_type=1&xmfcid=792ff0c2-dccb-4099-a43c-5c969ad60d0a-0-abf611255
  ROM_NAME: ZUI
  BUILD_TYPE: Aonly
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' $GITHUB_WORKSPACE/ErfanGSIs/url2GSI.sh
       
       - name: Setting up ErfanGSI requirements
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs
              mkdir ./output
              sudo bash ./setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: |
              cd  $GITHUB_WORKSPACE/ErfanGSIs
              sudo bash ./url2GSI.sh -c --$BUILD_TYPE $ROM_URL $ROM_NAME
       
       - name: Zip GSI  
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              mkdir final
              zip -r final/GSI.zip ./*

       - name: Upload GSI to WeTransfer
         run: |
              cd $GITHUB_WORKSPACE/ErfanGSIs/output
              curl -sL https://git.io/file-transfer | sh
              ./transfer gof ./final/GSI.zip


         
            
